name: build and publish extension

on:
   push:
      branches:
         - master
      paths-ignore: # dont run when changes made to these folders
         - '.vscode/**'

jobs:
   publish:
      name: build & publish
      runs-on: ubuntu-latest
      steps:
         - name: checkout repo
           uses: actions/checkout@v2

         - name: 'Automated Version Bump'
           uses: 'phips28/gh-action-bump-version@master'
           with:
              tag-prefix: 'release'

         - name: setup node
           uses: actions/setup-node@v1
           with:
              node-version: '12.x'

         - name: clean install dependencies
           run: npm ci

         - name: build extension
           run: npm run vscode:package

         - name: publish to marketplace
           run: npx vsce publish -p $VSCE_TOKEN
           env:
              VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
