name: build and publish extension

on:
   push:
      branches:
         - main
      paths-ignore: # dont run when changes made to these folders
         - '.vscode/**'

jobs:
   publish:
      name: build & publish
      runs-on: ubuntu-latest
      steps:
         - name: checkout repo
           uses: actions/checkout@v2

         - name: setup node
           uses: actions/setup-node@v1
           with:
              node-version: '14.x'

         - name: install dependencies
           run: npm i

         - name: 'Automated Version Bump'
           uses: 'phips28/gh-action-bump-version@master'
           with:
              tag-prefix: 'release'

         - name: build extension
           run: npm run vscode:package

         - name: publish to marketplace
           run: npx vsce publish -p $VSCE_TOKEN
           env:
             VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

         - name: get-npm-version
           id: package-version
           uses: martinbeentjes/npm-get-version-action@master

         - name: upload .vsix as artifact
           uses: actions/upload-artifact@v1
           with:
             name: git-assistant-${{ steps.package-version.outputs.current-version }}.vsix
             path: ${{ github.workspace }}/git-assistant-${{ steps.package-version.outputs.current-version }}.vsix